site_name: Siddhi-Runner-Beam
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi Execution Beam: index.md
- API Docs:
- License: about/license.md
theme: material